image: trion/ng-cli-karma

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - npm cache clear --force
   - npm i @angular/cli
   - npm install
   - npm rebuild node-sass
   - npm run generate-docs
   - ./node_modules/.bin/ng build --prod --base-href . --output-path www/
  artifacts:
    paths:
      -  www/
      -  documentation/
  variables:
    DOCKER_DRIVER: overlay

test:
  stage: test
  script:
    - ./node_modules/.bin/ng test --code-coverage=true
  artifacts:
    paths:
      - coverage/
  coverage: '/(\d*.?\d+)%/'

pages:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - ls
    - mv documentation www/
    - mv coverage/ www/
    - mv www/ public
    - ls public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
